
name: TTC_EXAMPLE
log_dir: logs
chkpt_dir: checkpoint
use_checkpoints: true

device: GPU

model:
    name: Net

dataset:
    name: MNISTV2
    transforms: MNISTTransformsV2
    root: data
    loader_args:
        batch_size: 128
        num_workers: 2
        shuffle: True
        pin_memory: True

loss: CrossEntropyLoss

optimizer:
    type: SGD
    args:
        lr: 0.01
        momentum: 0.95

training:
    epochs: 5

